version: '3.6'
services:
  db:
    container_name: mariadb-countries
    image: mariadb:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    environment:
      MARIADB_ROOT_PASSWORD: sup4rs3cure
      MARIADB_USER: johnny
      MARIADB_PASSWORD: s3cr4T
      MARIADB_DATABASE: countries
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network
      
  web:
    container_name: con-app-php-apache
    image: ghcr.io/diacles/devops-web:latest
    volumes:
      - ./:/var/www/html/  # Montez tout le répertoire courant
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network
      
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 con-app-php-apache  # Surveille uniquement le conteneur web toutes les 30 secondes
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge